export const fieldLabels: Record<string, string> = {
  patientName: 'Nombre del Paciente',
  patientId: 'DNI del Paciente',
  examType: 'Tipo de Examen',
  date: 'Fecha de Reporte',
  sampleDate: 'Fecha de Muestra',
  resultado: 'Resultado',
  hematocrit: 'Hematocrito',
  hemoglobin: 'Hemoglobina',
  rbc: 'Glóbulos Rojos (10^6/µL)',
  wbc: 'Glóbulos Blancos (10³/µL)',
  platelets: 'Plaquetas (10³/µL)',
  observations: 'Observaciones',
  color: 'Color',
  clarity: 'Claridad',
  ph: 'pH',
  glucose: 'Glucosa',
  ketones: 'Cetonas',
  microscopicObservations: 'Análisis Microscópico',
  physicochemicalAnalysis: 'Análisis Físico-químico',
  microbiologicalAnalysis: 'Análisis Microbiológico',
  fasting: 'En Ayunas',
  glucoseLevel: 'Nivel de Glucosa',
  patientAge: 'Edad',
  hcn: 'HCN (Historia Clínica)',
  bloodGroup: 'Grupo Sanguíneo',
  rhFactor: 'Factor Rh',
  syphilisTest: 'Prueba Rápida de Sífilis',
  hivTest: 'Prueba Rápida de V.I.H.',
  pregnancyTest: 'Test de Embarazo en Sangre',
  parasitologyDirectExam: 'Examen Parasitológico Directo',
  rbcCount: 'Recuento de Hematíes',
  wbcCount: 'Recuento de Leucocitos',
  neutrophilsBanded: 'Neutrófilos (Abastonados)',
  neutrophilsSegmented: 'Neutrófilos (Segmentados)',
  lymphocytes: 'Linfocitos',
  monocytes: 'Monocitos',
  eosinophils: 'Eosinófilos',
  basophils: 'Basófilos',
  metamyelocytes: 'Metamielocitos',
  myelocytes: 'Mielocitos',
  promyelocytes: 'Promielocitos',
  blasts: 'Blastos',
  mcv: 'V.C.M.',
  mch: 'H.C.M.',
  mchc: 'C.H.C.M.',
  plateletCount: 'Recuento de Plaquetas',
  coagulationTime: 'Tiempo de Coagulación',
  bleedingTime: 'Tiempo de Sangría',
  esr: 'V.S.G.',
  triglycerides: 'Triglicéridos',
  cholesterol: 'Colesterol',
  colesterol: 'Colesterol',
  ldl: 'L.D.L',
  hdl: 'H.D.L',
  creatinine: 'Creatinina',
  urea: 'Urea',
  uricAcid: 'Ácido Úrico',
  amylase: 'Amilasa',
  tgo: 'T.G.O.',
  tgp: 'T.G.P.',
  bilirubinTotal: 'Bilirrubina Total',
  bilirubinDirect: 'Bilirrubina Directa',
  bilirubinIndirect: 'Bilirrubina Indirecta',
  alkalinePhosphatase: 'Fosfatasa Alcalina',
  agglutinations: 'Aglutinaciones',
  aso: 'ASO',
  rheumatoidFactor: 'Factor Reumatoide',
  crp: 'Proteína C Reactiva (PCR)',
  psaTest: 'Prueba rápida de Antígeno Prostático',
  h_pyloriTest: 'Prueba rápida de Helicobacter Pylori',
  fobTest: 'Prueba rápida de Sangre Oculta',
  rprVrdl: 'RPR / VDRL',
  urineColor: 'Color (Orina)',
  urineAspect: 'Aspecto (Orina)',
  urineDensity: 'Densidad (Orina)',
  urinePh: 'pH (Orina)',
  urineAscorbicAcid: 'Ácido Ascórbico',
  urineBilirubin: 'Bilirrubina',
  urineUrobilinogen: 'Urobilinógeno',
  urineKetones: 'Cetonas',
  urineGlucose: 'Glucosa',
  urineProteins: 'Proteínas',
  urineBlood: 'Sangre',
  urineNitrites: 'Nitritos',
  urineLeukocytes: 'Leucocitos',
  urineEpithelialCells: 'Células Epiteliales',
  urineRbc: 'Hematíes',
  urineWbc: 'Leucocitos',
  urinePiocitos: 'Piocitos',
  urineBacteria: 'Bacterias',
  urineCylinders: 'Cilindros',
  urineCrystals: 'Cristales',
  urineOther: 'Otros',
  parasitologySerial: 'Examen Parasitológico Seriado',
  directMethod: 'M. Directo / M. Faust',
  grahamTest: 'Test de Graham',
  parasitologySample1: 'Examen Parasitológico - 1ra Muestra',
  parasitologySample2: 'Examen Parasitológico - 2da Muestra',
  parasitologySample3: 'Examen Parasitológico - 3ra Muestra',
  postPrandialGlucose: 'Glucosa Post Prandial',
  totalCholesterol: 'Colesterol Total',
  albumin: 'Albúminas',
  globulins: 'Globulinas',
  totalProteins: 'Proteínas Totales',
  macroColor: 'Color',
  macroConsistency: 'Consistencia',
  macroMucus: 'Moco',
  macroBlood: 'Sangre',
  microEpithelialCells: 'Células Epiteliales',
  microRbc: 'Hematíes',
  microWbc: 'Leucocitos',
  microPyocytes: 'Piocitos',
  microBiota: 'Microbiota',
  microOther: 'Otros',
}

export const suffixes: Record<string, string> = {
  hematocrit: '%',
  hemoglobin: 'g/dL',
  glucoseLevel: 'mg/dL',
  rbc: ' 10^6/µL',
  wbc: ' 10³/µL',
  platelets: ' 10³/µL',
  rbcCount: 'x10⁶/uL',
  wbcCount: 'x10³/uL',
  neutrophilsBanded: '%',
  neutrophilsSegmented: '%',
  lymphocytes: '%',
  monocytes: '%',
  eosinophils: '%',
  basophils: '%',
  metamyelocytes: '%',
  myelocytes: '%',
  promyelocytes: '%',
  blasts: '%',
  mcv: 'fL',
  mch: 'pg',
  mchc: 'g/dL',
  plateletCount: 'x10³/uL',
  glucose: 'mg/dl',
  creatinine: 'mg/dl',
  urea: 'mg/dl',
  uricAcid: 'mg/dl',
  postPrandialGlucose: 'mg/dl',
  totalCholesterol: 'mg/dl',
  hdl: 'mg/dl',
  ldl: 'mg/dl',
  triglycerides: 'mg/dl',
  tgo: 'U/L',
  tgp: 'U/L',
  alkalinePhosphatase: 'U/L',
  amylase: 'UA/dl',
  bilirubinTotal: 'mg/dl',
  bilirubinDirect: 'mg/dl',
  bilirubinIndirect: 'mg/dl',
  totalProteins: 'gr/dl',
  albumin: 'g/dL',
  globulins: 'g/dL',
}

export function getFieldLabel(key: string): string {
  return fieldLabels[key] || key
}

export function getFieldSuffix(key: string): string | undefined {
  return suffixes[key]
}
